download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-hrobot-2.7.0.tar.gz
format_version: 1.0.0
name: hrobot
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.7.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/hrobot/versions/2.7.0/
