download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/samdoran-macos-2.6.3.tar.gz
format_version: 1.0.0
name: macos
namespace: samdoran
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.6.3
version_url: /api/v3/plugin/ansible/content/published/collections/index/samdoran/macos/versions/2.6.3/
